server:
  port: 8762
  servlet:
    context-path: /miniprograms
spring:
  redis:
    redisson:
      config: classpath:redisson-single-dev.yml

bytedance:
  open:
    componentAppId: "your componentAppId"
    componentSecret: "your componentSecret"
    componentToken: "your componentToken"
    componentAesKey: "your componentAesKey"